CREATE DATABASE IF NOT EXISTS student_registration
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE student_registration;

CREATE TABLE IF NOT EXISTS students (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id CHAR(8) NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    gender ENUM('Male', 'Female') NULL,
    class VARCHAR(50) NOT NULL,
    contact VARCHAR(30) NULL,
    email VARCHAR(150) NULL,
    password_hash VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS gender ENUM('Male', 'Female') NULL AFTER age;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS student_id CHAR(8) NULL UNIQUE AFTER id;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS contact VARCHAR(30) NULL AFTER class,
    ADD COLUMN IF NOT EXISTS email VARCHAR(150) NULL AFTER contact;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NULL AFTER email;